### ISSUE TITLE
NFS Decoding Issue - version 0.22.3

### ISSUE THREAD

**Issue by davidswarbrick** [MusicPlayerDaemon/MPD#1087]
### Describe the bug
When decoding music files from an NFS store audio becomes choppy after a few seconds, and skipping fails to work.
The issue is not seen when the system's mountpoint of the NFS store is used.
This issue may be related to  #779 , however I am running Arch Linux rather than a Windows host.
I have also experienced  #1054, however this bug is over NFS rather than SMB.

## Expected Behavior
Audio plays as expected, with no glitches.
When the music directory is set to the mountpoint of the NFS share by the system, MPD functions correctly. 
Example `~/.config/mpd/mpd.conf`, in which audio works correctly:
```
music_directory "/mnt/networkshare/Music/Library"
```

## Actual Behavior
When the NFS mount is instead specified in `~/.config/mpd/mpd.conf`:
```
 music_directory "nfs://192.168.0.101/export/Music/Library"
```
decoding errors occur after a few seconds. These errors are independent of filetype, and as the only change in configuration options is the addition of nfs it seems this may be the issue.

## Version

```
~ mpd --version
Music Player Daemon 0.22.3 (0.22.3)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local udisks nfs curl

Neighbor plugins:
 upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal solaris pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file io_uring archive alsa tidal qobuz curl ffmpeg nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmpe:// rtmps:// rtmpt:// rtmpte:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp:// tidal://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un
```

### Skip to next track
Recreating #1054 

```
client: [0] process command "playid "2""
playlist: play 1:"2020/Phoebe Bridgers/Punisher/03 Kyoto.flac"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
decoder_thread: probing plugin flac
decoder: audio_format=96000:24:2, seekable=true
exception: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
output: opened "pulse audio" (pulse) audio_format=96000:24:2
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "plchanges "2""
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "seek "1" "64""
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
exception: Decoder failed to seek
client: [0] command returned 3
player: played "2020/Phoebe Bridgers/Punisher/03 Kyoto.flac"
client: [0] process command "idle"
client: [0] command returned 1
playlist: stop
output: closed "pulse audio" (pulse)
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
```
### Choppy audio
Recreating #779
MP3 file:
```
client: [0] process command "playid "41""
playlist: play 0:"1975-79/The Beatles/Abbey Road/01 Come Together.mp3"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "plchanges "3""
client: [0] command returned 0
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
decoder_thread: probing plugin mad
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
decoder: audio_format=44100:24:2, seekable=true
client: [0] process command "status"
exception: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
output: opened "pulse audio" (pulse) audio_format=44100:24:2
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "status"
```

FLAC file:
```
client: [0] process command "addid "2020/Phoebe Bridgers/Punisher/03 Kyoto.flac""
client: [0] command returned 0
client: [0] process command "playid "42""
playlist: play 1:"2020/Phoebe Bridgers/Punisher/03 Kyoto.flac"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "plchanges "5""
client: [0] command returned 0
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
decoder_thread: probing plugin flac
decoder: audio_format=96000:24:2, seekable=true
output: opened "pulse audio" (pulse) audio_format=96000:24:2
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "plchanges "6""
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_UNPARSEABLE_STREAM
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_UNPARSEABLE_STREAM
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_UNPARSEABLE_STREAM
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_UNPARSEABLE_STREAM
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_UNPARSEABLE_STREAM
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_FRAME_CRC_MISMATCH
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_FRAME_CRC_MISMATCH
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_UNPARSEABLE_STREAM
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_FRAME_CRC_MISMATCH
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_UNPARSEABLE_STREAM
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_UNPARSEABLE_STREAM
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_UNPARSEABLE_STREAM
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_FRAME_CRC_MISMATCH
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
client: [0] process command "status"
client: [0] command returned 0
client: [0] process command "idle"
client: [0] command returned 1
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_UNPARSEABLE_STREAM
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_FRAME_CRC_MISMATCH
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_FRAME_CRC_MISMATCH
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_UNPARSEABLE_STREAM
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_UNPARSEABLE_STREAM
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_FRAME_CRC_MISMATCH
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_UNPARSEABLE_STREAM
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_UNPARSEABLE_STREAM
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_UNPARSEABLE_STREAM
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_FRAME_CRC_MISMATCH
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_FRAME_CRC_MISMATCH
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
client: [0] process command "status"
client: [0] command returned 0
```

`~/.config/mpd/mpd.conf`:
```
log_file           "syslog"
pid_file           "~/.config/mpd/pid"
state_file         "~/.config/mpd/state"
sticker_file       "~/.config/mpd/sticker.sql"
#music_directory "/mnt/networkshare/Music/Library"

music_directory "nfs://192.168.0.101/export/Music/Library"

database {
    plugin "proxy"
    host "192.168.0.101"
    port "6600"
}
playlist_directory "/mnt/networkshare/Music/Playlists"
audio_output {
        type            "pulse"
        name            "pulse audio"
}
```
I have also tried using an ALSA backend, or no `audio_output` specified, but these did not stop the bug.

Permissions of `/mnt/networkshare` (on local machine)
```
~ ls -alh /mnt/networkshare/Music
total 4.0K
drwxrwsr-x+ 1 david  100   32 Feb  5 16:33 .
drwxr-xr-x  7 david root 4.0K Feb  7 12:52 ..
drwxrwsr-x+ 1 david  100  242 Feb 14 01:12 Library
drwxrwsr-x+ 1 david  100  270 Feb 14 00:21 Playlists
```
The NFS share is configured with `insecure` as per [the documentation.](https://www.musicpd.org/doc/html/plugins.html#input-nfs)
Thanks in advance for any help you can offer with this!

**Comment by MaxKellermann** [comment]
Which libnfs version?

**Comment by a-dekker** [comment]
There is an issue with libnfs in combination with certain recent 5.10.x kernels on the nfs server side that should be solved in kernel 5.10.15.
It also effects my kodi video playback via libnfs (stuttering, skipping parts), although music playing music still seems okay. Using a regular mount solves this.

See for example https://github.com/xbmc/xbmc/issues/19147

Not sure if this is related, but I would check before diving deeper in mpd itself.

**Comment by davidswarbrick** [comment]
libnfs version: local/libnfs 4.0.0-4
kernel: 5.10.8-arch1-1.
I can report back when I've upgraded to the latest kernel.

**Comment by davidswarbrick** [comment]
Issue still present on kernel 5.11.1-arch1-1, libnfs unchanged.

**Comment by davidswarbrick** [comment]
I've managed to recreate this bug on a Raspberry Pi:

```
~ mpd --version
Music Player Daemon 0.21.5 (0.21.5)

Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2018 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local smbclient udisks nfs curl

Neighbor plugins:
 smbclient upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsdiff] dff
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve
 [gme] ay gbs gym hes kss nsf nsfe sap spc vgm vgz
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo pipe alsa ao oss openal pulse jack httpd recorder

Encoder plugins:
 null vorbis opus lame wave flac

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa tidal qobuz curl ffmpeg smbclient nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// tidal:// qobuz:// http:// https:// gopher:// rtp:// rtsp:// rtmp:// rtmpt:// rtmps:// smb:// nfs:// mms:// mmsh:// mmst:// mmsu:// cdda://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un
~ uname -a
Linux raspberrypi3 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l GNU/Linux

~ sudo mpd --stderr --no-daemon --verbose
[sudo] password for david:
config_file: loading file /etc/mpd.conf
exception: bind to '0.0.0.0:6600' failed (continuing anyway, because binding to '[::]:6600' succeeded): Failed to bind socket: Address already in use
path: SetFSCharset: fs charset is:
libsamplerate: libsamplerate converter 'Fastest Sinc Interpolator'
vorbis: Xiph.Org libVorbis 1.3.6
opus: libopus 1.3
sndfile: libsndfile-1.0.28
wildmidi: configuration file does not exist: /etc/timidity/timidity.cfg
adplug: adplug 2.2.1
curl: version 7.64.0
curl: with GnuTLS/3.6.7
avahi: Initializing interface
exception: RTIOThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
avahi: Client changed to state 2
avahi: Client is RUNNING
avahi: Registering service _mpd._tcp/Music Player @ raspberrypi3
avahi: Service group changed to state 0
avahi: Service group is UNCOMMITED
state_file: Loading state file /var/lib/mpd/state
exception: OutputThread could not get realtime scheduling, continuing anyway: sched_setscheduler failed: Operation not permitted
avahi: Service group changed to state 1
avahi: Service group is REGISTERING
decoder_thread: probing plugin flac
decoder: audio_format=44100:24:2, seekable=true
alsa_output: opened default type=PLUG
alsa_output: buffer: size=444..32768 time=10068..743039
alsa_output: period: size=444..32768 time=10068..743039
alsa_output: default period_time = buffer_time/4 = 500000/4 = 125000
alsa_output: format=S24_LE (Signed 24 bit Little Endian)
alsa_output: buffer_size=22050 period_size=5512
output: opened "My ALSA Device" (alsa) audio_format=44100:24:2
exception: Failed to open mixer for 'My ALSA Device': no such mixer control: PCM
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_BAD_HEADER
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_UNPARSEABLE_STREAM
flac: FLAC__STREAM_DECODER_ERROR_STATUS_LOST_SYNC
flac: FLAC__STREAM_DECODER_ERROR_STATUS_FRAME_CRC_MISMATCH
```

Configuration:
```
# An example configuration file for MPD.
# Read the user manual for documentation: http://www.musicpd.org/doc/user/
# or /usr/share/doc/mpd/html/user.html


# Files and directories #######################################################
#
# This setting controls the top directory which MPD will search to discover the
# available audio files and add them to the daemon's online database. This
# setting defaults to the XDG directory, otherwise the music directory will be
# be disabled and audio files will only be accepted over ipc socket (using
# file:// protocol) or streaming files over an accepted protocol.
#
#music_directory                "/var/lib/mpd/music"
music_directory "nfs://192.168.0.101/export/Music/Library"
#
# This setting sets the MPD internal playlist directory. The purpose of this
# directory is storage for playlists created by MPD. The server will use
# playlist files not created by the server but only if they are in the MPD
# format. This setting defaults to playlist saving being disabled.
#
#playlist_directory             "/var/lib/mpd/playlists"
#
# This setting sets the location of the MPD database. This file is used to
# load the database at server start up and store the database while the
# server is not up. This setting defaults to disabled which will allow
# MPD to accept files over ipc socket (using file:// protocol) or streaming
# files over an accepted protocol.
#
#db_file                        "/var/lib/mpd/tag_cache"
#
# These settings are the locations for the daemon log files for the daemon.
# These logs are great for troubleshooting, depending on your log_level
# settings.
#
# The special value "syslog" makes MPD use the local syslog daemon. This
# setting defaults to logging to syslog, or to journal if mpd was started as
# a systemd service.
#
log_file                        "/var/log/mpd/mpd.log"
#
# This setting sets the location of the file which stores the process ID
# for use of mpd --kill and some init scripts. This setting is disabled by
# default and the pid file will not be stored.
#
pid_file                        "/run/mpd/pid"
#
# This setting sets the location of the file which contains information about
# most variables to get MPD back into the same general shape it was in before
# it was brought down. This setting is disabled by default and the server
# state will be reset on server start up.
#
state_file                      "/var/lib/mpd/state"
#
# The location of the sticker database.  This is a database which
# manages dynamic information attached to songs.
#
sticker_file                   "/var/lib/mpd/sticker.sql"
#
###############################################################################


# General music daemon options ################################################
#
# This setting specifies the user that MPD will run as. MPD should never run as
# root and you may use this setting to make MPD change its user ID after
# initialization. This setting is disabled by default and MPD is run as the
# current user.
#
user                            "mpd"
#
# This setting specifies the group that MPD will run as. If not specified
# primary group of user specified with "user" setting will be used (if set).
# This is useful if MPD needs to be a member of group such as "audio" to
# have permission to use sound card.
#
#group                          "nogroup"
#
# This setting sets the address for the daemon to listen on. Careful attention
# should be paid if this is assigned to anything other then the default, any.
# This setting can deny access to control of the daemon. Choose any if you want
# to have mpd listen on every address. Not effective if systemd socket
# activation is in use.
#
# For network
#bind_to_address                "localhost"
bind_to_address         "any"
#
# And for Unix Socket
#bind_to_address                "/run/mpd/socket"
#
# This setting is the TCP port that is desired for the daemon to get assigned
# to.
#
#port                           "6600"
#
# This setting controls the type of information which is logged. Available
# setting arguments are "default", "secure" or "verbose". The "verbose" setting
# argument is recommended for troubleshooting, though can quickly stretch
# available resources on limited hardware storage.
#
#log_level                      "default"
#
# Setting "restore_paused" to "yes" puts MPD into pause mode instead
# of starting playback after startup.
#
#restore_paused "no"
#
# This setting enables MPD to create playlists in a format usable by other
# music players.
#
#save_absolute_paths_in_playlists       "no"
#
# This setting defines a list of tag types that will be extracted during the
# audio file discovery process. The complete list of possible values can be
# found in the user manual.
#metadata_to_use        "artist,album,title,track,name,genre,date,composer,performer,disc"
#
# This example just enables the "comment" tag without disabling all
# the other supported tags:
#metadata_to_use "+comment"
#
# This setting enables automatic update of MPD's database when files in
# music_directory are changed.
#
#auto_update    "yes"
#
# Limit the depth of the directories being watched, 0 means only watch
# the music directory itself.  There is no limit by default.
#
#auto_update_depth "3"
#
###############################################################################


# Symbolic link behavior ######################################################
#
# If this setting is set to "yes", MPD will discover audio files by following
# symbolic links outside of the configured music_directory.
#
#follow_outside_symlinks        "yes"
#
# If this setting is set to "yes", MPD will discover audio files by following
# symbolic links inside of the configured music_directory.
#
#follow_inside_symlinks         "yes"
#
###############################################################################


# Zeroconf / Avahi Service Discovery ##########################################
#
# If this setting is set to "yes", service information will be published with
# Zeroconf / Avahi.
#
#zeroconf_enabled               "yes"
#
# The argument to this setting will be the Zeroconf / Avahi unique name for
# this MPD server on the network. %h will be replaced with the hostname.
#
#zeroconf_name                  "Music Player @ %h"
#
###############################################################################


# Permissions #################################################################
#
# If this setting is set, MPD will require password authorization. The password
# setting can be specified multiple times for different password profiles.
#
#password                        "password@read,add,control,admin"
#
# This setting specifies the permissions a user has who has not yet logged in.
#
#default_permissions             "read,add,control,admin"
#
###############################################################################


# Database #######################################################################
#

database {
       plugin "proxy"
       host "192.168.0.101"
       port "6600"
}

# Input #######################################################################
#

input {
        plugin "curl"
#       proxy "proxy.isp.com:8080"
#       proxy_user "user"
#       proxy_password "password"
}

# QOBUZ input plugin
input {
        enabled    "no"
        plugin     "qobuz"
#        app_id     "ID"
#        app_secret "SECRET"
#        username   "USERNAME"
#        password   "PASSWORD"
#        format_id  "N"
}

# TIDAL input plugin
input {
        enabled      "no"
        plugin       "tidal"
#        token        "TOKEN"
#        username     "USERNAME"
#        password     "PASSWORD"
#        audioquality "Q"
}

# Decoder #####################################################################
#

decoder {
        plugin                  "hybrid_dsd"
        enabled                 "no"
#       gapless                 "no"
}

#
###############################################################################

# Audio Output ################################################################
#
# MPD supports various audio output types, as well as playing through multiple
# audio outputs at the same time, through multiple audio_output settings
# blocks. Setting this block is optional, though the server will only attempt
# autodetection for one sound card.
#
# An example of an ALSA output:
#
audio_output {
        type            "alsa"
        name            "My ALSA Device"
#       device          "hw:0,0"        # optional
#       mixer_type      "hardware"      # optional
#       mixer_device    "default"       # optional
#       mixer_control   "PCM"           # optional
#       mixer_index     "0"             # optional
}
#
# An example of an OSS output:
#
#audio_output {
#       type            "oss"
#       name            "My OSS Device"
#       device          "/dev/dsp"      # optional
#       mixer_type      "hardware"      # optional
#       mixer_device    "/dev/mixer"    # optional
#       mixer_control   "PCM"           # optional
#}
#
# An example of a shout output (for streaming to Icecast):
#
#audio_output {
#       type            "shout"
#       encoder         "vorbis"                # optional
#       name            "My Shout Stream"
#       host            "localhost"
#       port            "8000"
#       mount           "/mpd.ogg"
#       password        "hackme"
#       quality         "5.0"
#       bitrate         "128"
#       format          "44100:16:1"
#       protocol        "icecast2"              # optional
#       user            "source"                # optional
#       description     "My Stream Description" # optional
#       url             "http://example.com"    # optional
#       genre           "jazz"                  # optional
#       public          "no"                    # optional
#       timeout         "2"                     # optional
#       mixer_type      "software"              # optional
#}
#
# An example of a recorder output:
#
#audio_output {
#       type            "recorder"
#       name            "My recorder"
#       encoder         "vorbis"                # optional, vorbis or lame
#       path            "/var/lib/mpd/recorder/mpd.ogg"
##      quality         "5.0"                   # do not define if bitrate is defined
#       bitrate         "128"                   # do not define if quality is defined
#       format          "44100:16:1"
#}
#
# An example of a httpd output (built-in HTTP streaming server):
#
#audio_output {
#       type            "httpd"
#       name            "My HTTP Stream"
#       encoder         "vorbis"                # optional, vorbis or lame
#       port            "8000"
#       bind_to_address "0.0.0.0"               # optional, IPv4 or IPv6
#       quality         "5.0"                   # do not define if bitrate is defined
#       bitrate         "128"                   # do not define if quality is defined
#       format          "44100:16:1"
#       max_clients     "0"                     # optional 0=no limit
#}
#
# An example of a pulseaudio output (streaming to a remote pulseaudio server)
# Please see README.Debian if you want mpd to play through the pulseaudio
# daemon started as part of your graphical desktop session!
#
#audio_output {
#       type            "pulse"
#       name            "My Pulse Output"
#       server          "remote_server"         # optional
#       sink            "remote_server_sink"    # optional
#}
#
# An example of a winmm output (Windows multimedia API).
#
#audio_output {
#       type            "winmm"
#       name            "My WinMM output"
#       device          "Digital Audio (S/PDIF) (High Definition Audio Device)" # optional
#               or
#       device          "0"             # optional
#       mixer_type      "hardware"      # optional
#}
#
# An example of an openal output.
#
#audio_output {
#       type            "openal"
#       name            "My OpenAL output"
#       device          "Digital Audio (S/PDIF) (High Definition Audio Device)" # optional
#}
#
## Example "pipe" output:
#
#audio_output {
#       type            "pipe"
#       name            "my pipe"
#       command         "aplay -f cd 2>/dev/null"
## Or if you're want to use AudioCompress
#       command         "AudioCompress -m | aplay -f cd 2>/dev/null"
## Or to send raw PCM stream through PCM:
#       command         "nc example.org 8765"
#       format          "44100:16:2"
#}
#
## An example of a null output (for no audio output):
#
#audio_output {
#       type            "null"
#       name            "My Null Output"
#       mixer_type      "none"                  # optional
#}
#
###############################################################################


# Normalization automatic volume adjustments ##################################
#
# This setting specifies the type of ReplayGain to use. This setting can have
# the argument "off", "album", "track" or "auto". "auto" is a special mode that
# chooses between "track" and "album" depending on the current state of
# random playback. If random playback is enabled then "track" mode is used.
# See <http://www.replaygain.org> for more details about ReplayGain.
# This setting is off by default.
#
#replaygain                     "album"
#
# This setting sets the pre-amp used for files that have ReplayGain tags. By
# default this setting is disabled.
#
#replaygain_preamp              "0"
#
# This setting sets the pre-amp used for files that do NOT have ReplayGain tags.
# By default this setting is disabled.
#
#replaygain_missing_preamp      "0"
#
# This setting enables or disables ReplayGain limiting.
# MPD calculates actual amplification based on the ReplayGain tags
# and replaygain_preamp / replaygain_missing_preamp setting.
# If replaygain_limit is enabled MPD will never amplify audio signal
# above its original level. If replaygain_limit is disabled such amplification
# might occur. By default this setting is enabled.
#
#replaygain_limit               "yes"
#
# This setting enables on-the-fly normalization volume adjustment. This will
# result in the volume of all playing audio to be adjusted so the output has
# equal "loudness". This setting is disabled by default.
#
#volume_normalization           "no"
#
###############################################################################

# Character Encoding ##########################################################
#
# If file or directory names do not display correctly for your locale then you
# may need to modify this setting.
#
filesystem_charset              "UTF-8"
#
###############################################################################
```

**Comment by davidswarbrick** [comment]
There is a chance this could be due to a server-side issue as proposed by @a-dekker since it is running 5.10.12. Will attempt to upgrade the NFS server kernel and report results once it is >5.10.15.

**Comment by davidswarbrick** [comment]
NFS server upgraded to 5.10.16 fixed playback via MPD, i.e. the configuration above:
```
music_directory "nfs://192.168.0.101/export/Music/Library"
```
is now working for playback, so this issue can be closed.

**Comment by oddfacade** [comment]
possibly unrelated, but since this is literally the only search result I got when I had the same symptoms with mpd 0.24.3 on gentoo: using mpg123 as the decoder plugin for mp3 files can also cause this behavior. [it's clearly stated in the docs that this plugin only supports local files](https://mpd.readthedocs.io/en/latest/plugins.html#mpg123) so no need to change anything. just wanted to leave a comment here to hopefully save someone else a bit of frustration... the fix is to disable that plugin. i just compiled it out of the binary, but i assume there's also a configuration option.

**Comment by MaxKellermann** [comment]
@oddfacade, the docs are outdated and streaming with mpg123 has been working for a while already. If it weren't, then this plugin simply wouldn't be used and a different mp3 plugin would be used. Therefore disabling this doesn't possibly solve such a problem, ever.
If there are still problems, however, somebody should report them - I have never heard of such a problem. But your suggestion to disable the plugin isn't good advice. It's not helpful.
(This bug report here is unrelated and turned out to be bogus.)

**Comment by oddfacade** [comment]
@MaxKellermann I don't know what to tell you... removing mpg123 fixes seeking on NFS for me. I just recompiled mpd with mpg123 included again to double check, and sure enough that breaks it again. You would know better than me why this might be; I just know disabling the plugin is a viable workaround on my system. Forgive me for not being helpful.

**Comment by MaxKellermann** [comment]
> Forgive me for not being helpful.

How, if you still keep spamming this ticket with off-topic blather?

**Comment by oddfacade** [comment]
Yes, yes that sounds very upsetting. I opened #2326 with more details.
