### ISSUE TITLE
MPD crashes: terminate called after throwing an instance of 'std::logic_error'

### ISSUE THREAD

**Issue by c2b2pss** [MusicPlayerDaemon/MPD#1417]
### Describe the bug
mpd crashes immediately on startup. does not even scan music folder.  I built the program from source on Ubuntu 20. It installs, but starting up mpd just crashes.  Installing directly from 'apt' (sudo apt install mpd) works fine. No errors. **_And the old mpd.conf just works_.** with version 0.22 that is installed from apt. So that's interesting.

**Plot thickens**: If I download the source file for the apt pkg, from https://packages.ubuntu.com/source/hirsute/mpd, mpd_0.22.6.orig.tar.xz, compilation works but mpd again fails to start. ??

```
Jan 27 21:20 : decoder: Decoder plugin 'wildmidi' is unavailable: configuration file does not exist: /etc/timidity/timidity.cfg
Jan 27 21:20 : exception: Database corrupted
terminate called after throwing an instance of 'std::logic_error'
  what():  basic_string::_M_construct null not valid
Jan 27 21:20 : exception: MPD died from signal 6 (core dumped): No such file or directory
```

## Expected Behavior
Should start....for example, mpc >> MPD error: Connection refused

## Actual Behavior
Crashes - NO LOG OUTPUT, even though log file set up.

## Version

Music Player Daemon 0.24 (0.24)
Copyright 2003-2007 Warren Dukes <warren.dukes@gmail.com>
Copyright 2008-2021 Max Kellermann <max.kellermann@gmail.com>
This is free software; see the source for copying conditions.  There is NO
warranty; not even MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Database plugins:
 simple proxy upnp

Storage plugins:
 local udisks nfs curl

Neighbor plugins:
 upnp udisks

Decoders plugins:
 [mad] mp3 mp2
 [mpg123] mp3
 [vorbis] ogg oga
 [oggflac] ogg oga
 [flac] flac
 [opus] opus ogg oga
 [sndfile] wav aiff aif au snd paf iff svx sf voc w64 pvf xi htk caf sd2
 [audiofile] wav au aiff aif
 [dsf] dsf
 [hybrid_dsd] m4a
 [faad] aac
 [mpcdec] mpc
 [wavpack] wv
 [modplug] 669 amf ams dbm dfm dsm far it med mdl mod mtm mt2 okt s3m stm ult umx xm
 [mikmod] amf dsm far gdm imf it med mod mtm s3m stm stx ult uni xm
 [sidplay] sid mus str prg P00
 [wildmidi] mid
 [fluidsynth] mid
 [adplug] amd d00 hsc laa rad raw sa2
 [ffmpeg] 16sv 3g2 3gp 4xm 8svx aa3 aac ac3 adx afc aif aifc aiff al alaw amr anim apc ape asf atrac au aud avi avm2 avs bap bfi c93 cak cin cmv cpk daud dct divx dts dv dvd dxa eac3 film flac flc fli fll flx flv g726 gsm gxf iss m1v m2v m2t m2ts m4a m4b m4v mad mj2 mjpeg mjpg mka mkv mlp mm mmf mov mp+ mp1 mp2 mp3 mp4 mpc mpeg mpg mpga mpp mpu mve mvi mxf nc nsv nut nuv oga ogm ogv ogx oma ogg omg opus psp pva qcp qt r3d ra ram rl2 rm rmvb roq rpl rvc shn smk snd sol son spx str swf tak tgi tgq tgv thp ts tsp tta xa xvid uv uv2 vb vid vob voc vp6 vmd wav webm wma wmv wsaud wsvga wv wve rtp:// rtsp:// rtsps://
 [gme] ay gbs gym hes kss nsf nsfe rsn sap spc vgm vgz
 [dsdiff] dff
 [sacdiso] dat iso
 [dvdaiso] iso
 [pcm]

Filters:
 libsamplerate soxr

Tag plugins:
 id3tag

Output plugins:
 shout null fifo sndio pipe alsa ao openal pipewire pulse jack httpd snapcast recorder

Encoder plugins:
 null vorbis opus lame twolame wave flac shine

Archive plugins:
 [bz2] bz2
 [zzip] zip
 [iso] iso

Input plugins:
 file archive alsa qobuz curl ffmpeg nfs mms cdio_paranoia

Playlist plugins:
 extm3u m3u pls xspf asx rss soundcloud flac cue embcue

Protocols:
 file:// alsa:// cdda:// ftp:// ftps:// gopher:// hls+http:// hls+https:// http:// https:// mms:// mmsh:// mmst:// mmsu:// nfs:// qobuz:// rtmp:// rtmps:// rtmpt:// rtmpts:// rtp:// rtsp:// rtsps:// scp:// sftp:// smb:// srtp://

Other features:
 avahi dbus udisks epoll icu inotify ipv6 systemd tcp un

## Log

NO LOG GENERATED !!!

**Comment by MaxKellermann** [comment]
Need backtrace. See https://mpd.readthedocs.io/en/stable/user.html#crash

**Comment by c2b2pss** [comment]
Max,
The error was 'I think' in due to files of unrecognized format. After removing these files using

`mpd --no-daemon --stdout --verbose` 

and rebuilding from source, its is fixed.  Although, mpd should not get stuck ever on files, you can close this issue for now.  I am using a slightly different source which I will in my other open discussion.

Thanks again for the real timely repsonses!!!!

**Comment by c2b2pss** [comment]
Please close this issue for now.

**Comment by MaxKellermann** [comment]
No, please post a backtrace. This is a bug, and it's not fixed, even if you were successful making the crash go away for you.

**Comment by MaxKellermann** [comment]
Closing because @c2b2pss refuses to cooperate.
